name: insta_clone
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/instagram_logo.svg
    - assets/icons/facebook_icon.svg
    - assets/icons/back_icon.svg
    - assets/icons/camera_icon.svg
    - assets/icons/live_icon.svg
    - assets/icons/messanger_icon.svg
    - assets/images/stories/story1.png
    - assets/images/stories/story2.png
    - assets/images/stories/story3.png
    - assets/images/stories/story4.png
    - assets/images/stories/story5.png
    - assets/images/posts/post1.png
    - assets/images/posts/post2.png
    - assets/images/profiles/poster1.png
    - assets/images/profiles/my_profile.png
    - assets/icons/favorite.svg
    - assets/icons/comment_icon.svg
    - assets/icons/save_icon.svg
    - assets/icons/home.svg
    - assets/icons/search.svg
    - assets/icons/add.svg
    - assets/icons/verified_icon.svg
    - assets/icons/more_icon.svg
    - assets/icons/livestream_icon.svg
    - assets/images/profiles/liker1.png
